connect_timeout=5
network_timeout=30
base_path=/var/data/tmp_uploads
tracker_server=fastdfs-tracker:22122
log_level=info
use_connection_pool=false
load_fdfs_parameters_from_tracker=false
use_storage_id=false
storage_ids_filename=storage_ids.conf
http.tracker_server_port=8080
